layout_spectrum: 0.005922813
color:
  saturation: 0.9742291
  lightness: 0.4623656
  brandStrength: 1
  brandColors:
    - '#E0CEA4'
    - '#FDFBE1'
    - '#B39A78'
    - '#39282F'
    - '#A4B4BD'
  rhythmicContrast: 0.3043225
typography_spectrum: 0.9029921
name: AnthonyThienpont
